//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18033
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceLainsaSci {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLainsaSci() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceLainsaSci", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita número de acta.
        /// </summary>
        internal static string ActaNeeded {
            get {
                return ResourceManager.GetString("ActaNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta revisión es la última antes de que caduque el dispositivo el {0:dd/MM/yyyy}. Si desea dar de baja ahora un dispositivo confirme la fecha_apertura haciendo clic en &quot;OK&quot;..
        /// </summary>
        internal static string CaducidadProxima {
            get {
                return ResourceManager.GetString("CaducidadProxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita una categoría.
        /// </summary>
        internal static string CategoriaNeeded {
            get {
                return ResourceManager.GetString("CategoriaNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar registro.
        /// </summary>
        internal static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falló la eliminación del registro, posiblemente hay registros relacionados que impiden su borrado..
        /// </summary>
        internal static string DeleteRecordFail {
            get {
                return ResourceManager.GetString("DeleteRecordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea realmente borrar el registro?.
        /// </summary>
        internal static string DeleteRecordQuestion {
            get {
                return ResourceManager.GetString("DeleteRecordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden mostrar direcciones sin propietario.
        /// </summary>
        internal static string DirectionWithoutOwner {
            get {
                return ResourceManager.GetString("DirectionWithoutOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden mostrar correos sin propietario.
        /// </summary>
        internal static string EmailWithoutOwner {
            get {
                return ResourceManager.GetString("EmailWithoutOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita una emprea.
        /// </summary>
        internal static string EmpresaNeeded {
            get {
                return ResourceManager.GetString("EmpresaNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe el fichero modelo. Se necesita un fichero con nombre &apos;terminal.sdf&apos; en la carpeta BD del proyecto con la estructura correcta de la base de datos a exportar.
        /// </summary>
        internal static string ExportFile {
            get {
                return ResourceManager.GetString("ExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Femenino.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de nombre de fichero incorrecto. \nDebe de ser idEmpresa_*.sdf.
        /// </summary>
        internal static string Importar {
            get {
                return ResourceManager.GetString("Importar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe la empresa a importar.
        /// </summary>
        internal static string ImportEmpresa {
            get {
                return ResourceManager.GetString("ImportEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;b&gt;Bienvenido / bienvenida:&lt;/b&gt; &lt;p&gt;Recuerde sus obligaciones respecto del cumplimiento de la &lt;b&gt;LOPD&lt;/b&gt;.&lt;br/&gt;Si no las conoce, salga de la aplicación y hable con su Responsable de Fichero. &lt;/p&gt;.
        /// </summary>
        internal static string LegalNote {
            get {
                return ResourceManager.GetString("LegalNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita un login y contraseña.
        /// </summary>
        internal static string LoginAndPasswordNeeded {
            get {
                return ResourceManager.GetString("LoginAndPasswordNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos.
        /// </summary>
        internal static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita un login.
        /// </summary>
        internal static string LoginNeeded {
            get {
                return ResourceManager.GetString("LoginNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Masculino.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita un agente extintor.
        /// </summary>
        internal static string NcAgenteExtintor {
            get {
                return ResourceManager.GetString("NcAgenteExtintor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita un dispositivo.
        /// </summary>
        internal static string NcDispositivo {
            get {
                return ResourceManager.GetString("NcDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita un estado.
        /// </summary>
        internal static string NcEstado {
            get {
                return ResourceManager.GetString("NcEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita un fabricante.
        /// </summary>
        internal static string NcFabricante {
            get {
                return ResourceManager.GetString("NcFabricante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita una fecha_apertura de fabricación.
        /// </summary>
        internal static string NcFechaFabricacion {
            get {
                return ResourceManager.GetString("NcFechaFabricacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita una función.
        /// </summary>
        internal static string NcFuncion {
            get {
                return ResourceManager.GetString("NcFuncion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita al menos una instalación o un tipo de dispositivo.
        /// </summary>
        internal static string NcInformeEmpresa {
            get {
                return ResourceManager.GetString("NcInformeEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita una instalación.
        /// </summary>
        internal static string NcInstalacion {
            get {
                return ResourceManager.GetString("NcInstalacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita un modelo.
        /// </summary>
        internal static string NcModelo {
            get {
                return ResourceManager.GetString("NcModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita un tipo de dispositivo.
        /// </summary>
        internal static string NcTipoDispositivo {
            get {
                return ResourceManager.GetString("NcTipoDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra el fichero en disco.
        /// </summary>
        internal static string NDocumento {
            get {
                return ResourceManager.GetString("NDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita un tipo de campo.
        /// </summary>
        internal static string NecTipoCampo {
            get {
                return ResourceManager.GetString("NecTipoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita un tipo de dispositivo.
        /// </summary>
        internal static string NecTipoDispositivo {
            get {
                return ResourceManager.GetString("NecTipoDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita una fecha_apertura correcta.
        /// </summary>
        internal static string NeededCorrectDateTime {
            get {
                return ResourceManager.GetString("NeededCorrectDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita un nombre.
        /// </summary>
        internal static string NombreNeeded {
            get {
                return ResourceManager.GetString("NombreNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO se han asignado permisos para este proceso al grupo de este usuario..
        /// </summary>
        internal static string NoPermissionsAssigned {
            get {
                return ResourceManager.GetString("NoPermissionsAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de periodos no puede ser cero.
        /// </summary>
        internal static string NumeroPeriodosNoCero {
            get {
                return ResourceManager.GetString("NumeroPeriodosNoCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita un proceso padre.
        /// </summary>
        internal static string ParentProcessNeeded {
            get {
                return ResourceManager.GetString("ParentProcessNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        internal static string PasswordDoesntMatch {
            get {
                return ResourceManager.GetString("PasswordDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primario.
        /// </summary>
        internal static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha_apertura de revisión no debe ser inferior a la planificada.
        /// </summary>
        internal static string RevisionMenosPlanificacion {
            get {
                return ResourceManager.GetString("RevisionMenosPlanificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secundario.
        /// </summary>
        internal static string Secondary {
            get {
                return ResourceManager.GetString("Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden mostrar teléfonos sin propietarios.
        /// </summary>
        internal static string TelephoneWithoutOwner {
            get {
                return ResourceManager.GetString("TelephoneWithoutOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita un grupo de trabajo.
        /// </summary>
        internal static string TrabajoGroupNeeded {
            get {
                return ResourceManager.GetString("TrabajoGroupNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita un grupo de usuario.
        /// </summary>
        internal static string UsuarioGroupNeeded {
            get {
                return ResourceManager.GetString("UsuarioGroupNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
