//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18033
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Telerik.ReportViewer.WebForms {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Telerik.ReportViewer.WebForms.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página actula.
        /// </summary>
        internal static string CurrentPageToolTip {
            get {
                return ResourceManager.GetString("CurrentPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocultar mapa de documento|Mostrar mapa de documento.
        /// </summary>
        internal static string DocumentMapToolTip {
            get {
                return ResourceManager.GetString("DocumentMapToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar.
        /// </summary>
        internal static string ExportButtonText {
            get {
                return ResourceManager.GetString("ExportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar al formato seleccionado.
        /// </summary>
        internal static string ExportSelectFormatText {
            get {
                return ResourceManager.GetString("ExportSelectFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar.
        /// </summary>
        internal static string ExportToolTip {
            get {
                return ResourceManager.GetString("ExportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primera página.
        /// </summary>
        internal static string FirstPageToolTip {
            get {
                return ResourceManager.GetString("FirstPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        internal static string LabelOf {
            get {
                return ResourceManager.GetString("LabelOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Última página.
        /// </summary>
        internal static string LastPageToolTip {
            get {
                return ResourceManager.GetString("LastPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atrás.
        /// </summary>
        internal static string NavigateBackToolTip {
            get {
                return ResourceManager.GetString("NavigateBackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adelante.
        /// </summary>
        internal static string NavigateForwardToolTip {
            get {
                return ResourceManager.GetString("NavigateForwardToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página siguiente.
        /// </summary>
        internal static string NextPageToolTip {
            get {
                return ResourceManager.GetString("NextPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clic para cerrar área de parámetros|Clic para abrir área de parámetros.
        /// </summary>
        internal static string ParametersToolTip {
            get {
                return ResourceManager.GetString("ParametersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Páguina anterior.
        /// </summary>
        internal static string PreviousPageToolTip {
            get {
                return ResourceManager.GetString("PreviousPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        internal static string PrintToolTip {
            get {
                return ResourceManager.GetString("PrintToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generando informe....
        /// </summary>
        internal static string ProcessingReportMessage {
            get {
                return ResourceManager.GetString("ProcessingReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string RefreshToolTip {
            get {
                return ResourceManager.GetString("RefreshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falso.
        /// </summary>
        internal static string ReportParametersFalseValueLabel {
            get {
                return ResourceManager.GetString("ReportParametersFalseValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca datos para todos los parámetros..
        /// </summary>
        internal static string ReportParametersInputDataError {
            get {
                return ResourceManager.GetString("ReportParametersInputDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor no válido..
        /// </summary>
        internal static string ReportParametersInvalidValueText {
            get {
                return ResourceManager.GetString("ReportParametersInvalidValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor requerido.
        /// </summary>
        internal static string ReportParametersNoValueText {
            get {
                return ResourceManager.GetString("ReportParametersNoValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista previa.
        /// </summary>
        internal static string ReportParametersNullText {
            get {
                return ResourceManager.GetString("ReportParametersNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview.
        /// </summary>
        internal static string ReportParametersPreviewButtonText {
            get {
                return ResourceManager.GetString("ReportParametersPreviewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;seleccciona todo&gt;.
        /// </summary>
        internal static string ReportParametersSelectAllText {
            get {
                return ResourceManager.GetString("ReportParametersSelectAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;seleccciona un valor&gt;.
        /// </summary>
        internal static string ReportParametersSelectAValueText {
            get {
                return ResourceManager.GetString("ReportParametersSelectAValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verdadero.
        /// </summary>
        internal static string ReportParametersTrueValueLabel {
            get {
                return ResourceManager.GetString("ReportParametersTrueValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ancho de página.
        /// </summary>
        internal static string ZoomToPageWidth {
            get {
                return ResourceManager.GetString("ZoomToPageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página completa.
        /// </summary>
        internal static string ZoomToWholePage {
            get {
                return ResourceManager.GetString("ZoomToWholePage", resourceCulture);
            }
        }
    }
}
