//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class GrupoMensajesForm {
    
    /// <summary>
    /// RadStyleSheetManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadStyleSheetManager RadStyleSheetManager1;
    
    /// <summary>
    /// form1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    /// <summary>
    /// RadScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadScriptManager RadScriptManager1;
    
    /// <summary>
    /// RadCodeBlock1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadCodeBlock RadCodeBlock1;
    
    /// <summary>
    /// RadAjaxManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadAjaxManager RadAjaxManager1;
    
    /// <summary>
    /// RadSkinManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadSkinManager RadSkinManager1;
    
    /// <summary>
    /// lblGrupoMensajesId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblGrupoMensajesId;
    
    /// <summary>
    /// txtGrupoMensajesId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadTextBox txtGrupoMensajesId;
    
    /// <summary>
    /// lblNombre control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblNombre;
    
    /// <summary>
    /// txtNombre control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadTextBox txtNombre;
    
    /// <summary>
    /// valNombre control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.RequiredFieldValidator valNombre;
    
    /// <summary>
    /// btnAccept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ImageButton btnAccept;
    
    /// <summary>
    /// btnCancel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ImageButton btnCancel;
    
    /// <summary>
    /// RadNotification1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadNotification RadNotification1;
}
