//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class MensajeForm {
    
    /// <summary>
    /// RadStyleSheetManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadStyleSheetManager RadStyleSheetManager1;
    
    /// <summary>
    /// form1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    /// <summary>
    /// RadScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadScriptManager RadScriptManager1;
    
    /// <summary>
    /// RadCodeBlock1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadCodeBlock RadCodeBlock1;
    
    /// <summary>
    /// RadAjaxManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadAjaxManager RadAjaxManager1;
    
    /// <summary>
    /// RadSkinManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadSkinManager RadSkinManager1;
    
    /// <summary>
    /// lblMensajeId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblMensajeId;
    
    /// <summary>
    /// txtMensajeId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadTextBox txtMensajeId;
    
    /// <summary>
    /// lblGrupoMensajes control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblGrupoMensajes;
    
    /// <summary>
    /// imgbGrupoMensajes control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ImageButton imgbGrupoMensajes;
    
    /// <summary>
    /// rdcGrupoMensajes control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadComboBox rdcGrupoMensajes;
    
    /// <summary>
    /// lblTitulo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblTitulo;
    
    /// <summary>
    /// txtTitulo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadTextBox txtTitulo;
    
    /// <summary>
    /// valTitulo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.RequiredFieldValidator valTitulo;
    
    /// <summary>
    /// lblFechaInicio control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblFechaInicio;
    
    /// <summary>
    /// dtFechaInicio control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadDatePicker dtFechaInicio;
    
    /// <summary>
    /// lblFechaFin control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblFechaFin;
    
    /// <summary>
    /// dtFechaFin control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadDatePicker dtFechaFin;
    
    /// <summary>
    /// lblCuerpo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblCuerpo;
    
    /// <summary>
    /// rdeCuerpo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadEditor rdeCuerpo;
    
    /// <summary>
    /// btnAccept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ImageButton btnAccept;
    
    /// <summary>
    /// btnCancel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ImageButton btnCancel;
    
    /// <summary>
    /// RadNotification1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated grupo.
    /// To modify move grupo declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.Web.UI.RadNotification RadNotification1;
}
