#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using LainsaSciModelo;

namespace LainsaSciModelo	
{
	public partial class LainsaSci : OpenAccessContext, ILainsaSciUnitOfWork
	{
		private static string connectionStringName = @"Falck_sciConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntityDiagrams.rlinq");
		
		public LainsaSci()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public LainsaSci(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public LainsaSci(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public LainsaSci(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public LainsaSci(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Usuario> Usuarios 
		{
			get
			{
				return this.GetAll<Usuario>();
			}
		}
		
		public IQueryable<GrupoUsuario> GrupoUsuarios 
		{
			get
			{
				return this.GetAll<GrupoUsuario>();
			}
		}
		
		public IQueryable<Proceso> Procesos 
		{
			get
			{
				return this.GetAll<Proceso>();
			}
		}
		
		public IQueryable<Permiso> Permisos 
		{
			get
			{
				return this.GetAll<Permiso>();
			}
		}
		
		public IQueryable<Empresa> Empresas 
		{
			get
			{
				return this.GetAll<Empresa>();
			}
		}
		
		public IQueryable<Direccion> Direccions 
		{
			get
			{
				return this.GetAll<Direccion>();
			}
		}
		
		public IQueryable<Email> Emails 
		{
			get
			{
				return this.GetAll<Email>();
			}
		}
		
		public IQueryable<Telefono> Telefonos 
		{
			get
			{
				return this.GetAll<Telefono>();
			}
		}
		
		public IQueryable<UTPParametros> UTPParametros 
		{
			get
			{
				return this.GetAll<UTPParametros>();
			}
		}
		
		public IQueryable<Instalacion> Instalacions 
		{
			get
			{
				return this.GetAll<Instalacion>();
			}
		}
		
		public IQueryable<Operario> Operarios 
		{
			get
			{
				return this.GetAll<Operario>();
			}
		}
		
		public IQueryable<CarnetRadiologico> CarnetRadiologicos 
		{
			get
			{
				return this.GetAll<CarnetRadiologico>();
			}
		}
		
		public IQueryable<Dispositivo> Dispositivos 
		{
			get
			{
				return this.GetAll<Dispositivo>();
			}
		}
		
		public IQueryable<TipoDispositivo> TipoDispositivos 
		{
			get
			{
				return this.GetAll<TipoDispositivo>();
			}
		}
		
		public IQueryable<ModeloDispositivo> ModeloDispositivos 
		{
			get
			{
				return this.GetAll<ModeloDispositivo>();
			}
		}
		
		public IQueryable<PlantillaRevision> PlantillaRevisions 
		{
			get
			{
				return this.GetAll<PlantillaRevision>();
			}
		}
		
		public IQueryable<Campo> Campos 
		{
			get
			{
				return this.GetAll<Campo>();
			}
		}
		
		public IQueryable<TipoCampo> TipoCampos 
		{
			get
			{
				return this.GetAll<TipoCampo>();
			}
		}
		
		public IQueryable<Fabricante> Fabricantes 
		{
			get
			{
				return this.GetAll<Fabricante>();
			}
		}
		
		public IQueryable<AgenteExtintor> AgenteExtintors 
		{
			get
			{
				return this.GetAll<AgenteExtintor>();
			}
		}
		
		public IQueryable<Revision> Revisions 
		{
			get
			{
				return this.GetAll<Revision>();
			}
		}
		
		public IQueryable<DatosRevision> DatosRevisions 
		{
			get
			{
				return this.GetAll<DatosRevision>();
			}
		}
		
		public IQueryable<ResumenRevision> ResumenRevisions 
		{
			get
			{
				return this.GetAll<ResumenRevision>();
			}
		}
		
		public IQueryable<Programa> Programas 
		{
			get
			{
				return this.GetAll<Programa>();
			}
		}
		
		public IQueryable<Filtro> Filtros 
		{
			get
			{
				return this.GetAll<Filtro>();
			}
		}
		
		public IQueryable<Sustitucion> Sustitucions 
		{
			get
			{
				return this.GetAll<Sustitucion>();
			}
		}
		
		public IQueryable<Terminal> Terminals 
		{
			get
			{
				return this.GetAll<Terminal>();
			}
		}
		
		public IQueryable<CargaTerminales> CargaTerminales 
		{
			get
			{
				return this.GetAll<CargaTerminales>();
			}
		}
		
		public IQueryable<UsuarioExtranet> UsuarioExtranets 
		{
			get
			{
				return this.GetAll<UsuarioExtranet>();
			}
		}
		
		public IQueryable<Categoria> Categorias 
		{
			get
			{
				return this.GetAll<Categoria>();
			}
		}
		
		public IQueryable<Subcategoria> Subcategorias 
		{
			get
			{
				return this.GetAll<Subcategoria>();
			}
		}
		
		public IQueryable<Documento> Documentos 
		{
			get
			{
				return this.GetAll<Documento>();
			}
		}
		
		public IQueryable<GrupoMensajes> GrupoMensajes 
		{
			get
			{
				return this.GetAll<GrupoMensajes>();
			}
		}
		
		public IQueryable<Mensaje> Mensajes 
		{
			get
			{
				return this.GetAll<Mensaje>();
			}
		}
		
		public IQueryable<TipoAnomalia> TipoAnomalias 
		{
			get
			{
				return this.GetAll<TipoAnomalia>();
			}
		}
		
		public IQueryable<ProgramacionInforme> ProgramacionInformes 
		{
			get
			{
				return this.GetAll<ProgramacionInforme>();
			}
		}
		
		public IQueryable<InformeProgramado> InformeProgramados 
		{
			get
			{
				return this.GetAll<InformeProgramado>();
			}
		}
		
		public IQueryable<Plantilla> Plantillas 
		{
			get
			{
				return this.GetAll<Plantilla>();
			}
		}
		
		public IQueryable<CargaTerminal> CargaTerminals 
		{
			get
			{
				return this.GetAll<CargaTerminal>();
			}
		}
		
		public IQueryable<GrupoTrabajo> GrupoTrabajos 
		{
			get
			{
				return this.GetAll<GrupoTrabajo>();
			}
		}
		
		public IQueryable<Incidencia> Incidencias 
		{
			get
			{
				return this.GetAll<Incidencia>();
			}
		}
		
		public IQueryable<IncidenciaEvolucion> IncidenciaEvolucions 
		{
			get
			{
				return this.GetAll<IncidenciaEvolucion>();
			}
		}
		
		public IQueryable<Estado> Estados 
		{
			get
			{
				return this.GetAll<Estado>();
			}
		}
		
		public IQueryable<Prioridad> Prioridads 
		{
			get
			{
				return this.GetAll<Prioridad>();
			}
		}
		
		public IQueryable<Responsable> Responsables 
		{
			get
			{
				return this.GetAll<Responsable>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "mysql";
			backend.ProviderName = "MySql.Data.MySqlClient";
			return backend;
		}
	}
	
	public interface ILainsaSciUnitOfWork : IUnitOfWork
	{
		IQueryable<Usuario> Usuarios
		{
			get;
		}
		IQueryable<GrupoUsuario> GrupoUsuarios
		{
			get;
		}
		IQueryable<Proceso> Procesos
		{
			get;
		}
		IQueryable<Permiso> Permisos
		{
			get;
		}
		IQueryable<Empresa> Empresas
		{
			get;
		}
		IQueryable<Direccion> Direccions
		{
			get;
		}
		IQueryable<Email> Emails
		{
			get;
		}
		IQueryable<Telefono> Telefonos
		{
			get;
		}
		IQueryable<UTPParametros> UTPParametros
		{
			get;
		}
		IQueryable<Instalacion> Instalacions
		{
			get;
		}
		IQueryable<Operario> Operarios
		{
			get;
		}
		IQueryable<CarnetRadiologico> CarnetRadiologicos
		{
			get;
		}
		IQueryable<Dispositivo> Dispositivos
		{
			get;
		}
		IQueryable<TipoDispositivo> TipoDispositivos
		{
			get;
		}
		IQueryable<ModeloDispositivo> ModeloDispositivos
		{
			get;
		}
		IQueryable<PlantillaRevision> PlantillaRevisions
		{
			get;
		}
		IQueryable<Campo> Campos
		{
			get;
		}
		IQueryable<TipoCampo> TipoCampos
		{
			get;
		}
		IQueryable<Fabricante> Fabricantes
		{
			get;
		}
		IQueryable<AgenteExtintor> AgenteExtintors
		{
			get;
		}
		IQueryable<Revision> Revisions
		{
			get;
		}
		IQueryable<DatosRevision> DatosRevisions
		{
			get;
		}
		IQueryable<ResumenRevision> ResumenRevisions
		{
			get;
		}
		IQueryable<Programa> Programas
		{
			get;
		}
		IQueryable<Filtro> Filtros
		{
			get;
		}
		IQueryable<Sustitucion> Sustitucions
		{
			get;
		}
		IQueryable<Terminal> Terminals
		{
			get;
		}
		IQueryable<CargaTerminales> CargaTerminales
		{
			get;
		}
		IQueryable<UsuarioExtranet> UsuarioExtranets
		{
			get;
		}
		IQueryable<Categoria> Categorias
		{
			get;
		}
		IQueryable<Subcategoria> Subcategorias
		{
			get;
		}
		IQueryable<Documento> Documentos
		{
			get;
		}
		IQueryable<GrupoMensajes> GrupoMensajes
		{
			get;
		}
		IQueryable<Mensaje> Mensajes
		{
			get;
		}
		IQueryable<TipoAnomalia> TipoAnomalias
		{
			get;
		}
		IQueryable<ProgramacionInforme> ProgramacionInformes
		{
			get;
		}
		IQueryable<InformeProgramado> InformeProgramados
		{
			get;
		}
		IQueryable<Plantilla> Plantillas
		{
			get;
		}
		IQueryable<CargaTerminal> CargaTerminals
		{
			get;
		}
		IQueryable<GrupoTrabajo> GrupoTrabajos
		{
			get;
		}
		IQueryable<Incidencia> Incidencias
		{
			get;
		}
		IQueryable<IncidenciaEvolucion> IncidenciaEvolucions
		{
			get;
		}
		IQueryable<Estado> Estados
		{
			get;
		}
		IQueryable<Prioridad> Prioridads
		{
			get;
		}
		IQueryable<Responsable> Responsables
		{
			get;
		}
	}
}
namespace LainsaSciModelo	
{
	public partial class Usuario
	{
		private int _usuarioId;
		public virtual int UsuarioId
		{
			get
			{
				return this._usuarioId;
			}
			set
			{
				this._usuarioId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _login;
		public virtual string Login
		{
			get
			{
				return this._login;
			}
			set
			{
				this._login = value;
			}
		}
		
		private string _password;
		public virtual string Password
		{
			get
			{
				return this._password;
			}
			set
			{
				this._password = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
		private GrupoUsuario _grupoUsuario1;
		public virtual GrupoUsuario GrupoUsuario
		{
			get
			{
				return this._grupoUsuario1;
			}
			set
			{
				this._grupoUsuario1 = value;
			}
		}
		
		private GrupoTrabajo _grupoTrabajo;
		public virtual GrupoTrabajo GrupoTrabajo
		{
			get
			{
				return this._grupoTrabajo;
			}
			set
			{
				this._grupoTrabajo = value;
			}
		}
		
		private IList<Revision> _revisions = new List<Revision>();
		public virtual IList<Revision> Revisions
		{
			get
			{
				return this._revisions;
			}
		}
		
		private IList<Programa> _programas = new List<Programa>();
		public virtual IList<Programa> Programas
		{
			get
			{
				return this._programas;
			}
		}
		
		private IList<Sustitucion> _sustitucions = new List<Sustitucion>();
		public virtual IList<Sustitucion> Sustitucions
		{
			get
			{
				return this._sustitucions;
			}
		}
		
		private IList<Filtro> _filtros = new List<Filtro>();
		public virtual IList<Filtro> Filtros
		{
			get
			{
				return this._filtros;
			}
		}
		
		private IList<Incidencia> _incidencias = new List<Incidencia>();
		public virtual IList<Incidencia> Incidencias
		{
			get
			{
				return this._incidencias;
			}
		}
		
		private IList<IncidenciaEvolucion> _incidenciaEvolucions = new List<IncidenciaEvolucion>();
		public virtual IList<IncidenciaEvolucion> IncidenciaEvolucions
		{
			get
			{
				return this._incidenciaEvolucions;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class GrupoUsuario
	{
		private int _grupoUsuarioId;
		public virtual int GrupoUsuarioId
		{
			get
			{
				return this._grupoUsuarioId;
			}
			set
			{
				this._grupoUsuarioId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private IList<Permiso> _permisos = new List<Permiso>();
		public virtual IList<Permiso> Permisos
		{
			get
			{
				return this._permisos;
			}
		}
		
		private IList<Usuario> _usuarios1 = new List<Usuario>();
		public virtual IList<Usuario> Usuarios
		{
			get
			{
				return this._usuarios1;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Proceso
	{
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				this._descripcion = value;
			}
		}
		
		private Proceso _procesoPadre;
		public virtual Proceso ProcesoPadre
		{
			get
			{
				return this._procesoPadre;
			}
			set
			{
				this._procesoPadre = value;
			}
		}
		
		private IList<Proceso> _procesos = new List<Proceso>();
		public virtual IList<Proceso> Procesos
		{
			get
			{
				return this._procesos;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Permiso
	{
		private int _permisoId;
		public virtual int PermisoId
		{
			get
			{
				return this._permisoId;
			}
			set
			{
				this._permisoId = value;
			}
		}
		
		private bool _ver;
		public virtual bool Ver
		{
			get
			{
				return this._ver;
			}
			set
			{
				this._ver = value;
			}
		}
		
		private bool _crear;
		public virtual bool Crear
		{
			get
			{
				return this._crear;
			}
			set
			{
				this._crear = value;
			}
		}
		
		private bool _modificar;
		public virtual bool Modificar
		{
			get
			{
				return this._modificar;
			}
			set
			{
				this._modificar = value;
			}
		}
		
		private bool _especial;
		public virtual bool Especial
		{
			get
			{
				return this._especial;
			}
			set
			{
				this._especial = value;
			}
		}
		
		private GrupoUsuario _grupoUsuario;
		public virtual GrupoUsuario GrupoUsuario
		{
			get
			{
				return this._grupoUsuario;
			}
			set
			{
				this._grupoUsuario = value;
			}
		}
		
		private Proceso _proceso1;
		public virtual Proceso Proceso
		{
			get
			{
				return this._proceso1;
			}
			set
			{
				this._proceso1 = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Empresa
	{
		private int _empresaId;
		public virtual int EmpresaId
		{
			get
			{
				return this._empresaId;
			}
			set
			{
				this._empresaId = value;
			}
		}
		
		private string _codAx;
		public virtual string CodAx
		{
			get
			{
				return this._codAx;
			}
			set
			{
				this._codAx = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _personaContacto;
		public virtual string PersonaContacto
		{
			get
			{
				return this._personaContacto;
			}
			set
			{
				this._personaContacto = value;
			}
		}
		
		private IList<Direccion> _direcciones = new List<Direccion>();
		public virtual IList<Direccion> Direcciones
		{
			get
			{
				return this._direcciones;
			}
		}
		
		private IList<Email> _emails = new List<Email>();
		public virtual IList<Email> Emails
		{
			get
			{
				return this._emails;
			}
		}
		
		private IList<Telefono> _telefonos = new List<Telefono>();
		public virtual IList<Telefono> Telefonos
		{
			get
			{
				return this._telefonos;
			}
		}
		
		private IList<Instalacion> _instalaciones = new List<Instalacion>();
		public virtual IList<Instalacion> Instalaciones
		{
			get
			{
				return this._instalaciones;
			}
		}
		
		private IList<Usuario> _usuarios = new List<Usuario>();
		public virtual IList<Usuario> Usuarios
		{
			get
			{
				return this._usuarios;
			}
		}
		
		private IList<TipoDispositivo> _tipoDispositivos = new List<TipoDispositivo>();
		public virtual IList<TipoDispositivo> TipoDispositivos
		{
			get
			{
				return this._tipoDispositivos;
			}
		}
		
		private IList<ModeloDispositivo> _modeloDispositivos = new List<ModeloDispositivo>();
		public virtual IList<ModeloDispositivo> ModeloDispositivos
		{
			get
			{
				return this._modeloDispositivos;
			}
		}
		
		private IList<Terminal> _terminals = new List<Terminal>();
		public virtual IList<Terminal> Terminals
		{
			get
			{
				return this._terminals;
			}
		}
		
		private IList<UsuarioExtranet> _usuarioExtranets = new List<UsuarioExtranet>();
		public virtual IList<UsuarioExtranet> UsuarioExtranets
		{
			get
			{
				return this._usuarioExtranets;
			}
		}
		
		private IList<Documento> _documentos = new List<Documento>();
		public virtual IList<Documento> Documentos
		{
			get
			{
				return this._documentos;
			}
		}
		
		private IList<InformeProgramado> _informeProgramados = new List<InformeProgramado>();
		public virtual IList<InformeProgramado> InformeProgramados
		{
			get
			{
				return this._informeProgramados;
			}
		}
		
		private IList<CargaTerminales> _cargaTerminals = new List<CargaTerminales>();
		public virtual IList<CargaTerminales> CargaTerminals
		{
			get
			{
				return this._cargaTerminals;
			}
		}
		
		private IList<Estado> _estados = new List<Estado>();
		public virtual IList<Estado> Estados
		{
			get
			{
				return this._estados;
			}
		}
		
		private IList<Responsable> _responsables = new List<Responsable>();
		public virtual IList<Responsable> Responsables
		{
			get
			{
				return this._responsables;
			}
		}
		
		private IList<Prioridad> _prioridads = new List<Prioridad>();
		public virtual IList<Prioridad> Prioridads
		{
			get
			{
				return this._prioridads;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Direccion
	{
		private int _direccionId;
		public virtual int DireccionId
		{
			get
			{
				return this._direccionId;
			}
			set
			{
				this._direccionId = value;
			}
		}
		
		private string _poblacion;
		public virtual string Poblacion
		{
			get
			{
				return this._poblacion;
			}
			set
			{
				this._poblacion = value;
			}
		}
		
		private string _codPostal;
		public virtual string CodPostal
		{
			get
			{
				return this._codPostal;
			}
			set
			{
				this._codPostal = value;
			}
		}
		
		private string _provincia;
		public virtual string Provincia
		{
			get
			{
				return this._provincia;
			}
			set
			{
				this._provincia = value;
			}
		}
		
		private string _pais;
		public virtual string Pais
		{
			get
			{
				return this._pais;
			}
			set
			{
				this._pais = value;
			}
		}
		
		private string _descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				this._descripcion = value;
			}
		}
		
		private string _dirPostal;
		public virtual string DirPostal
		{
			get
			{
				return this._dirPostal;
			}
			set
			{
				this._dirPostal = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Email
	{
		private int _emailId;
		public virtual int EmailId
		{
			get
			{
				return this._emailId;
			}
			set
			{
				this._emailId = value;
			}
		}
		
		private string _mail;
		public virtual string Mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				this._mail = value;
			}
		}
		
		private bool _envio;
		public virtual bool Envio
		{
			get
			{
				return this._envio;
			}
			set
			{
				this._envio = value;
			}
		}
		
		private string _descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				this._descripcion = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Telefono
	{
		private int _telefonoId;
		public virtual int TelefonoId
		{
			get
			{
				return this._telefonoId;
			}
			set
			{
				this._telefonoId = value;
			}
		}
		
		private string _tipo;
		public virtual string Tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				this._tipo = value;
			}
		}
		
		private string _numero;
		public virtual string Numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				this._numero = value;
			}
		}
		
		private string _descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				this._descripcion = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class UTPParametros
	{
		private int _uTPParametrosId;
		public virtual int UTPParametrosId
		{
			get
			{
				return this._uTPParametrosId;
			}
			set
			{
				this._uTPParametrosId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _direccion;
		public virtual string Direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				this._direccion = value;
			}
		}
		
		private string _telefono;
		public virtual string Telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				this._telefono = value;
			}
		}
		
		private string _mail;
		public virtual string Mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				this._mail = value;
			}
		}
		
		private decimal _maxDosisSuperficial;
		public virtual decimal MaxDosisSuperficial
		{
			get
			{
				return this._maxDosisSuperficial;
			}
			set
			{
				this._maxDosisSuperficial = value;
			}
		}
		
		private decimal _maxDosisSuperficalPeriodo;
		public virtual decimal MaxDosisSuperficalPeriodo
		{
			get
			{
				return this._maxDosisSuperficalPeriodo;
			}
			set
			{
				this._maxDosisSuperficalPeriodo = value;
			}
		}
		
		private decimal _maxDosisProfunda;
		public virtual decimal MaxDosisProfunda
		{
			get
			{
				return this._maxDosisProfunda;
			}
			set
			{
				this._maxDosisProfunda = value;
			}
		}
		
		private decimal _maxDosisProfundaPeriodo;
		public virtual decimal MaxDosisProfundaPeriodo
		{
			get
			{
				return this._maxDosisProfundaPeriodo;
			}
			set
			{
				this._maxDosisProfundaPeriodo = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Instalacion
	{
		private int _instalacionId;
		public virtual int InstalacionId
		{
			get
			{
				return this._instalacionId;
			}
			set
			{
				this._instalacionId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _codAx;
		public virtual string CodAx
		{
			get
			{
				return this._codAx;
			}
			set
			{
				this._codAx = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private IList<Direccion> _direcciones = new List<Direccion>();
		public virtual IList<Direccion> Direcciones
		{
			get
			{
				return this._direcciones;
			}
		}
		
		private IList<Email> _emails = new List<Email>();
		public virtual IList<Email> Emails
		{
			get
			{
				return this._emails;
			}
		}
		
		private IList<Telefono> _telefonos = new List<Telefono>();
		public virtual IList<Telefono> Telefonos
		{
			get
			{
				return this._telefonos;
			}
		}
		
		private IList<Operario> _operarios = new List<Operario>();
		public virtual IList<Operario> Operarios
		{
			get
			{
				return this._operarios;
			}
		}
		
		private IList<Dispositivo> _dispositivos = new List<Dispositivo>();
		public virtual IList<Dispositivo> Dispositivos
		{
			get
			{
				return this._dispositivos;
			}
		}
		
		private IList<Usuario> _usuarios = new List<Usuario>();
		public virtual IList<Usuario> Usuarios
		{
			get
			{
				return this._usuarios;
			}
		}
		
		private IList<TipoDispositivo> _tipoDispositivos = new List<TipoDispositivo>();
		public virtual IList<TipoDispositivo> TipoDispositivos
		{
			get
			{
				return this._tipoDispositivos;
			}
		}
		
		private IList<ModeloDispositivo> _modeloDispositivos = new List<ModeloDispositivo>();
		public virtual IList<ModeloDispositivo> ModeloDispositivos
		{
			get
			{
				return this._modeloDispositivos;
			}
		}
		
		private IList<UsuarioExtranet> _usuarioExtranets = new List<UsuarioExtranet>();
		public virtual IList<UsuarioExtranet> UsuarioExtranets
		{
			get
			{
				return this._usuarioExtranets;
			}
		}
		
		private IList<Documento> _documentos = new List<Documento>();
		public virtual IList<Documento> Documentos
		{
			get
			{
				return this._documentos;
			}
		}
		
		private IList<InformeProgramado> _informeProgramados = new List<InformeProgramado>();
		public virtual IList<InformeProgramado> InformeProgramados
		{
			get
			{
				return this._informeProgramados;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Operario
	{
		private int _operarioId;
		public virtual int OperarioId
		{
			get
			{
				return this._operarioId;
			}
			set
			{
				this._operarioId = value;
			}
		}
		
		private string _dni;
		public virtual string Dni
		{
			get
			{
				return this._dni;
			}
			set
			{
				this._dni = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private DateTime _fechaNacimiento;
		public virtual DateTime fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				this._fechaNacimiento = value;
			}
		}
		
		private Char _sexo;
		public virtual Char Sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				this._sexo = value;
			}
		}
		
		private string _codAx;
		public virtual string CodAx
		{
			get
			{
				return this._codAx;
			}
			set
			{
				this._codAx = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
		private CarnetRadiologico _carnetRadiologico;
		public virtual CarnetRadiologico CarnetRadiologico
		{
			get
			{
				return this._carnetRadiologico;
			}
			set
			{
				this._carnetRadiologico = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class CarnetRadiologico
	{
		private int _carnetId;
		public virtual int CarnetId
		{
			get
			{
				return this._carnetId;
			}
			set
			{
				this._carnetId = value;
			}
		}
		
		private string _numero;
		public virtual string Numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				this._numero = value;
			}
		}
		
		private DateTime _fechaEmision;
		public virtual DateTime fechaEmision
		{
			get
			{
				return this._fechaEmision;
			}
			set
			{
				this._fechaEmision = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Dispositivo
	{
		private int _dispositivoId;
		public virtual int DispositivoId
		{
			get
			{
				return this._dispositivoId;
			}
			set
			{
				this._dispositivoId = value;
			}
		}
		
		private DateTime _fechaFabricacion;
		public virtual DateTime FechaFabricacion
		{
			get
			{
				return this._fechaFabricacion;
			}
			set
			{
				this._fechaFabricacion = value;
			}
		}
		
		private DateTime _fechaCaducidad;
		public virtual DateTime FechaCaducidad
		{
			get
			{
				return this._fechaCaducidad;
			}
			set
			{
				this._fechaCaducidad = value;
			}
		}
		
		private string _posicion;
		public virtual string Posicion
		{
			get
			{
				return this._posicion;
			}
			set
			{
				this._posicion = value;
			}
		}
		
		private string _comentarios;
		public virtual string Comentarios
		{
			get
			{
				return this._comentarios;
			}
			set
			{
				this._comentarios = value;
			}
		}
		
		private DateTime _fechaInicioRevision;
		public virtual DateTime FechaInicioRevision
		{
			get
			{
				return this._fechaInicioRevision;
			}
			set
			{
				this._fechaInicioRevision = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _numeroIndustria;
		public virtual string NumeroIndustria
		{
			get
			{
				return this._numeroIndustria;
			}
			set
			{
				this._numeroIndustria = value;
			}
		}
		
		private bool _caducado;
		public virtual bool Caducado
		{
			get
			{
				return this._caducado;
			}
			set
			{
				this._caducado = value;
			}
		}
		
		private DateTime _fechaBaja;
		public virtual DateTime FechaBaja
		{
			get
			{
				return this._fechaBaja;
			}
			set
			{
				this._fechaBaja = value;
			}
		}
		
		private string _funcion;
		public virtual string Funcion
		{
			get
			{
				return this._funcion;
			}
			set
			{
				this._funcion = value;
			}
		}
		
		private string _estado;
		public virtual string Estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				this._estado = value;
			}
		}
		
		private string _codBarras;
		public virtual string CodBarras
		{
			get
			{
				return this._codBarras;
			}
			set
			{
				this._codBarras = value;
			}
		}
		
		private decimal _cargaKg;
		public virtual decimal CargaKg
		{
			get
			{
				return this._cargaKg;
			}
			set
			{
				this._cargaKg = value;
			}
		}
		
		private bool _operativo;
		public virtual bool Operativo
		{
			get
			{
				return this._operativo;
			}
			set
			{
				this._operativo = value;
			}
		}
		
		private bool _siguePlan;
		public virtual bool SiguePlan
		{
			get
			{
				return this._siguePlan;
			}
			set
			{
				this._siguePlan = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
		private TipoDispositivo _tipoDispositivo;
		public virtual TipoDispositivo TipoDispositivo
		{
			get
			{
				return this._tipoDispositivo;
			}
			set
			{
				this._tipoDispositivo = value;
			}
		}
		
		private ModeloDispositivo _modeloDispositivo;
		public virtual ModeloDispositivo ModeloDispositivo
		{
			get
			{
				return this._modeloDispositivo;
			}
			set
			{
				this._modeloDispositivo = value;
			}
		}
		
		private Dispositivo _dispositivoPadre;
		public virtual Dispositivo DispositivoPadre
		{
			get
			{
				return this._dispositivoPadre;
			}
			set
			{
				this._dispositivoPadre = value;
			}
		}
		
		private Fabricante _fabricante;
		public virtual Fabricante Fabricante
		{
			get
			{
				return this._fabricante;
			}
			set
			{
				this._fabricante = value;
			}
		}
		
		private AgenteExtintor _agenteExtintor;
		public virtual AgenteExtintor AgenteExtintor
		{
			get
			{
				return this._agenteExtintor;
			}
			set
			{
				this._agenteExtintor = value;
			}
		}
		
		private IList<Dispositivo> _accesorios = new List<Dispositivo>();
		public virtual IList<Dispositivo> Accesorios
		{
			get
			{
				return this._accesorios;
			}
		}
		
		private IList<Revision> _revisiones = new List<Revision>();
		public virtual IList<Revision> Revisiones
		{
			get
			{
				return this._revisiones;
			}
		}
		
		private IList<ResumenRevision> _resumenesRevisones = new List<ResumenRevision>();
		public virtual IList<ResumenRevision> ResumenesRevisones
		{
			get
			{
				return this._resumenesRevisones;
			}
		}
		
		private IList<Incidencia> _incidencias = new List<Incidencia>();
		public virtual IList<Incidencia> Incidencias
		{
			get
			{
				return this._incidencias;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class TipoDispositivo
	{
		private int _tipoId;
		public virtual int TipoId
		{
			get
			{
				return this._tipoId;
			}
			set
			{
				this._tipoId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private int _caduca;
		public virtual int Caduca
		{
			get
			{
				return this._caduca;
			}
			set
			{
				this._caduca = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
		private IList<PlantillaRevision> _plantillaRevisions = new List<PlantillaRevision>();
		public virtual IList<PlantillaRevision> PlantillaRevisions
		{
			get
			{
				return this._plantillaRevisions;
			}
		}
		
		private IList<ModeloDispositivo> _modeloDispositivos = new List<ModeloDispositivo>();
		public virtual IList<ModeloDispositivo> ModelosDispositivo
		{
			get
			{
				return this._modeloDispositivos;
			}
		}
		
		private IList<Documento> _documentos = new List<Documento>();
		public virtual IList<Documento> Documentos
		{
			get
			{
				return this._documentos;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class ModeloDispositivo
	{
		private int _modeloId;
		public virtual int ModeloId
		{
			get
			{
				return this._modeloId;
			}
			set
			{
				this._modeloId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private decimal _cargaKg;
		public virtual decimal CargaKg
		{
			get
			{
				return this._cargaKg;
			}
			set
			{
				this._cargaKg = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private TipoDispositivo _tipoDispositivo;
		public virtual TipoDispositivo TipoDispositivo
		{
			get
			{
				return this._tipoDispositivo;
			}
			set
			{
				this._tipoDispositivo = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class PlantillaRevision
	{
		private int _plantillaId;
		public virtual int PlantillaId
		{
			get
			{
				return this._plantillaId;
			}
			set
			{
				this._plantillaId = value;
			}
		}
		
		private string _descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				this._descripcion = value;
			}
		}
		
		private string _comentarios;
		public virtual string Comentarios
		{
			get
			{
				return this._comentarios;
			}
			set
			{
				this._comentarios = value;
			}
		}
		
		private string _tipoPeriodo;
		public virtual string TipoPeriodo
		{
			get
			{
				return this._tipoPeriodo;
			}
			set
			{
				this._tipoPeriodo = value;
			}
		}
		
		private int _numeroPeriodos;
		public virtual int NumeroPeriodos
		{
			get
			{
				return this._numeroPeriodos;
			}
			set
			{
				this._numeroPeriodos = value;
			}
		}
		
		private bool _conSustitucion;
		public virtual bool ConSustitucion
		{
			get
			{
				return this._conSustitucion;
			}
			set
			{
				this._conSustitucion = value;
			}
		}
		
		private bool _facturable;
		public virtual bool Facturable
		{
			get
			{
				return this._facturable;
			}
			set
			{
				this._facturable = value;
			}
		}
		
		private bool _noPeriodica;
		public virtual bool NoPeriodica
		{
			get
			{
				return this._noPeriodica;
			}
			set
			{
				this._noPeriodica = value;
			}
		}
		
		private TipoDispositivo _tipoDispositivo;
		public virtual TipoDispositivo TipoDispositivo
		{
			get
			{
				return this._tipoDispositivo;
			}
			set
			{
				this._tipoDispositivo = value;
			}
		}
		
		private IList<Campo> _campos = new List<Campo>();
		public virtual IList<Campo> Campos
		{
			get
			{
				return this._campos;
			}
		}
		
		private IList<Revision> _revisions = new List<Revision>();
		public virtual IList<Revision> Revisions
		{
			get
			{
				return this._revisions;
			}
		}
		
		private IList<ResumenRevision> _resumenesRevisones = new List<ResumenRevision>();
		public virtual IList<ResumenRevision> ResumenesRevisones
		{
			get
			{
				return this._resumenesRevisones;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Campo
	{
		private int _campoId;
		public virtual int CampoId
		{
			get
			{
				return this._campoId;
			}
			set
			{
				this._campoId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private int _posicion;
		public virtual int Posicion
		{
			get
			{
				return this._posicion;
			}
			set
			{
				this._posicion = value;
			}
		}
		
		private string _informaDe;
		public virtual string InformaDe
		{
			get
			{
				return this._informaDe;
			}
			set
			{
				this._informaDe = value;
			}
		}
		
		private PlantillaRevision _plantillaRevision1;
		public virtual PlantillaRevision PlantillaRevision
		{
			get
			{
				return this._plantillaRevision1;
			}
			set
			{
				this._plantillaRevision1 = value;
			}
		}
		
		private TipoCampo _tipoCampo;
		public virtual TipoCampo TipoCampo
		{
			get
			{
				return this._tipoCampo;
			}
			set
			{
				this._tipoCampo = value;
			}
		}
		
		private IList<DatosRevision> _datosRevisions = new List<DatosRevision>();
		public virtual IList<DatosRevision> DatosRevisions
		{
			get
			{
				return this._datosRevisions;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class TipoCampo
	{
		private int _tipoId;
		public virtual int TipoId
		{
			get
			{
				return this._tipoId;
			}
			set
			{
				this._tipoId = value;
			}
		}
		
		private string _descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				this._descripcion = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Fabricante
	{
		private int _fabricanteId;
		public virtual int FabricanteId
		{
			get
			{
				return this._fabricanteId;
			}
			set
			{
				this._fabricanteId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private IList<Dispositivo> _dispositivos = new List<Dispositivo>();
		public virtual IList<Dispositivo> Dispositivos
		{
			get
			{
				return this._dispositivos;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class AgenteExtintor
	{
		private int _agenteExtintorId;
		public virtual int AgenteExtintorId
		{
			get
			{
				return this._agenteExtintorId;
			}
			set
			{
				this._agenteExtintorId = value;
			}
		}
		
		private string _descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				this._descripcion = value;
			}
		}
		
		private IList<Dispositivo> _dispositivos = new List<Dispositivo>();
		public virtual IList<Dispositivo> Dispositivos
		{
			get
			{
				return this._dispositivos;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Revision
	{
		private int _revisionId;
		public virtual int RevisionId
		{
			get
			{
				return this._revisionId;
			}
			set
			{
				this._revisionId = value;
			}
		}
		
		private DateTime _fechaRevision;
		public virtual DateTime FechaRevision
		{
			get
			{
				return this._fechaRevision;
			}
			set
			{
				this._fechaRevision = value;
			}
		}
		
		private string _resultado;
		public virtual string Resultado
		{
			get
			{
				return this._resultado;
			}
			set
			{
				this._resultado = value;
			}
		}
		
		private string _observaciones;
		public virtual string Observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				this._observaciones = value;
			}
		}
		
		private string _estado;
		public virtual string Estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				this._estado = value;
			}
		}
		
		private DateTime _fechaProgramada;
		public virtual DateTime FechaProgramada
		{
			get
			{
				return this._fechaProgramada;
			}
			set
			{
				this._fechaProgramada = value;
			}
		}
		
		private DateTime _fechaPlanificada;
		public virtual DateTime FechaPlanificada
		{
			get
			{
				return this._fechaPlanificada;
			}
			set
			{
				this._fechaPlanificada = value;
			}
		}
		
		private bool _caduProx;
		public virtual bool CaduProx
		{
			get
			{
				return this._caduProx;
			}
			set
			{
				this._caduProx = value;
			}
		}
		
		private string _resumenInforme;
		public virtual string ResumenInforme
		{
			get
			{
				return this._resumenInforme;
			}
			set
			{
				this._resumenInforme = value;
			}
		}
		
		private int _grupoProgramacion;
		public virtual int GrupoProgramacion
		{
			get
			{
				return this._grupoProgramacion;
			}
			set
			{
				this._grupoProgramacion = value;
			}
		}
		
		private string _codBarras;
		public virtual string CodBarras
		{
			get
			{
				return this._codBarras;
			}
			set
			{
				this._codBarras = value;
			}
		}
		
		private Usuario _usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				this._usuario = value;
			}
		}
		
		private PlantillaRevision _plantillaRevision;
		public virtual PlantillaRevision PlantillaRevision
		{
			get
			{
				return this._plantillaRevision;
			}
			set
			{
				this._plantillaRevision = value;
			}
		}
		
		private Dispositivo _dispositivo;
		public virtual Dispositivo Dispositivo
		{
			get
			{
				return this._dispositivo;
			}
			set
			{
				this._dispositivo = value;
			}
		}
		
		private Programa _programa;
		public virtual Programa Programa
		{
			get
			{
				return this._programa;
			}
			set
			{
				this._programa = value;
			}
		}
		
		private TipoAnomalia _tipoAnomalia;
		public virtual TipoAnomalia TipoAnomalia
		{
			get
			{
				return this._tipoAnomalia;
			}
			set
			{
				this._tipoAnomalia = value;
			}
		}
		
		private IList<DatosRevision> _datosRevisions = new List<DatosRevision>();
		public virtual IList<DatosRevision> DatosRevisions
		{
			get
			{
				return this._datosRevisions;
			}
		}
		
		private IList<Sustitucion> _sustitucions = new List<Sustitucion>();
		public virtual IList<Sustitucion> Sustitucions
		{
			get
			{
				return this._sustitucions;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class DatosRevision
	{
		private int _datosId;
		public virtual int DatosId
		{
			get
			{
				return this._datosId;
			}
			set
			{
				this._datosId = value;
			}
		}
		
		private string _valor;
		public virtual string Valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				this._valor = value;
			}
		}
		
		private Campo _campo;
		public virtual Campo Campo
		{
			get
			{
				return this._campo;
			}
			set
			{
				this._campo = value;
			}
		}
		
		private Revision _revision;
		public virtual Revision Revision
		{
			get
			{
				return this._revision;
			}
			set
			{
				this._revision = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class ResumenRevision
	{
		private int _resumenRevisionId;
		public virtual int ResumenRevisionId
		{
			get
			{
				return this._resumenRevisionId;
			}
			set
			{
				this._resumenRevisionId = value;
			}
		}
		
		private DateTime _fechaInicio;
		public virtual DateTime FechaInicio
		{
			get
			{
				return this._fechaInicio;
			}
			set
			{
				this._fechaInicio = value;
			}
		}
		
		private DateTime _fechaSiguiente;
		public virtual DateTime FechaSiguiente
		{
			get
			{
				return this._fechaSiguiente;
			}
			set
			{
				this._fechaSiguiente = value;
			}
		}
		
		private DateTime _fechaUltima;
		public virtual DateTime FechaUltima
		{
			get
			{
				return this._fechaUltima;
			}
			set
			{
				this._fechaUltima = value;
			}
		}
		
		private Dispositivo _dispositivo;
		public virtual Dispositivo Dispositivo
		{
			get
			{
				return this._dispositivo;
			}
			set
			{
				this._dispositivo = value;
			}
		}
		
		private PlantillaRevision _plantillaRevision;
		public virtual PlantillaRevision PlantillaRevision
		{
			get
			{
				return this._plantillaRevision;
			}
			set
			{
				this._plantillaRevision = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Programa
	{
		private int _programaId;
		public virtual int ProgramaId
		{
			get
			{
				return this._programaId;
			}
			set
			{
				this._programaId = value;
			}
		}
		
		private string _comentarios;
		public virtual string Comentarios
		{
			get
			{
				return this._comentarios;
			}
			set
			{
				this._comentarios = value;
			}
		}
		
		private DateTime _fechaProgramada;
		public virtual DateTime FechaProgramada
		{
			get
			{
				return this._fechaProgramada;
			}
			set
			{
				this._fechaProgramada = value;
			}
		}
		
		private string _estado;
		public virtual string Estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				this._estado = value;
			}
		}
		
		private Usuario _usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				this._usuario = value;
			}
		}
		
		private CargaTerminal _cargaTerminal;
		public virtual CargaTerminal CargaTerminal
		{
			get
			{
				return this._cargaTerminal;
			}
			set
			{
				this._cargaTerminal = value;
			}
		}
		
		private Terminal _terminal;
		public virtual Terminal Terminal
		{
			get
			{
				return this._terminal;
			}
			set
			{
				this._terminal = value;
			}
		}
		
		private IList<Revision> _revisions = new List<Revision>();
		public virtual IList<Revision> Revisions
		{
			get
			{
				return this._revisions;
			}
		}
		
		private IList<Sustitucion> _sustitucions = new List<Sustitucion>();
		public virtual IList<Sustitucion> Sustitucions
		{
			get
			{
				return this._sustitucions;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Filtro
	{
		private int _filtroId;
		public virtual int FiltroId
		{
			get
			{
				return this._filtroId;
			}
			set
			{
				this._filtroId = value;
			}
		}
		
		private string _tipo;
		public virtual string Tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				this._tipo = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _expresion;
		public virtual string Expresion
		{
			get
			{
				return this._expresion;
			}
			set
			{
				this._expresion = value;
			}
		}
		
		private Usuario _usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				this._usuario = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Sustitucion
	{
		private int _sustitucionId;
		public virtual int SustitucionId
		{
			get
			{
				return this._sustitucionId;
			}
			set
			{
				this._sustitucionId = value;
			}
		}
		
		private DateTime _fecha;
		public virtual DateTime Fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				this._fecha = value;
			}
		}
		
		private string _comentarios;
		public virtual string Comentarios
		{
			get
			{
				return this._comentarios;
			}
			set
			{
				this._comentarios = value;
			}
		}
		
		private string _estado;
		public virtual string Estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				this._estado = value;
			}
		}
		
		private Usuario _usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				this._usuario = value;
			}
		}
		
		private Dispositivo _dispositivo;
		public virtual Dispositivo DispositivoOriginal
		{
			get
			{
				return this._dispositivo;
			}
			set
			{
				this._dispositivo = value;
			}
		}
		
		private Dispositivo _dispositivo1;
		public virtual Dispositivo DispositivoSustituto
		{
			get
			{
				return this._dispositivo1;
			}
			set
			{
				this._dispositivo1 = value;
			}
		}
		
		private Revision _revision;
		public virtual Revision Revision
		{
			get
			{
				return this._revision;
			}
			set
			{
				this._revision = value;
			}
		}
		
		private Programa _programa;
		public virtual Programa Programa
		{
			get
			{
				return this._programa;
			}
			set
			{
				this._programa = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Terminal
	{
		private int _terminalId;
		public virtual int TerminalId
		{
			get
			{
				return this._terminalId;
			}
			set
			{
				this._terminalId = value;
			}
		}
		
		private string _tipo;
		public virtual string Tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				this._tipo = value;
			}
		}
		
		private string _numeroSerie;
		public virtual string NumeroSerie
		{
			get
			{
				return this._numeroSerie;
			}
			set
			{
				this._numeroSerie = value;
			}
		}
		
		private string _observaciones;
		public virtual string Observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				this._observaciones = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private IList<CargaTerminal> _cargaTerminals = new List<CargaTerminal>();
		public virtual IList<CargaTerminal> CargaTerminals
		{
			get
			{
				return this._cargaTerminals;
			}
		}
		
		private IList<Programa> _programas = new List<Programa>();
		public virtual IList<Programa> Programas
		{
			get
			{
				return this._programas;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class CargaTerminal
	{
		private int _cargaTerminalId;
		public virtual int CargaTerminalId
		{
			get
			{
				return this._cargaTerminalId;
			}
			set
			{
				this._cargaTerminalId = value;
			}
		}
		
		private DateTime _fecha;
		public virtual DateTime Fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				this._fecha = value;
			}
		}
		
		private string _fichero;
		public virtual string Fichero
		{
			get
			{
				return this._fichero;
			}
			set
			{
				this._fichero = value;
			}
		}
		
		private string _observaciones;
		public virtual string Observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				this._observaciones = value;
			}
		}
		
		private Terminal _terminal;
		public virtual Terminal Terminal
		{
			get
			{
				return this._terminal;
			}
			set
			{
				this._terminal = value;
			}
		}
		
		private IList<Programa> _programas = new List<Programa>();
		public virtual IList<Programa> Programas
		{
			get
			{
				return this._programas;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class UsuarioExtranet
	{
		private int _usuarioExtranetId;
		public virtual int UsuarioExtranetId
		{
			get
			{
				return this._usuarioExtranetId;
			}
			set
			{
				this._usuarioExtranetId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _login;
		public virtual string Login
		{
			get
			{
				return this._login;
			}
			set
			{
				this._login = value;
			}
		}
		
		private string _password;
		public virtual string Password
		{
			get
			{
				return this._password;
			}
			set
			{
				this._password = value;
			}
		}
		
		private string _plainPassword;
		public virtual string PlainPassword
		{
			get
			{
				return this._plainPassword;
			}
			set
			{
				this._plainPassword = value;
			}
		}
		
		private string _correo;
		public virtual string Correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				this._correo = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Categoria
	{
		private int _categoriaId;
		public virtual int CategoriaId
		{
			get
			{
				return this._categoriaId;
			}
			set
			{
				this._categoriaId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private IList<Subcategoria> _subcategorias = new List<Subcategoria>();
		public virtual IList<Subcategoria> Subcategorias
		{
			get
			{
				return this._subcategorias;
			}
		}
		
		private IList<Documento> _documentos = new List<Documento>();
		public virtual IList<Documento> Documentos
		{
			get
			{
				return this._documentos;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Subcategoria
	{
		private int _subcategoriaId;
		public virtual int SubcategoriaId
		{
			get
			{
				return this._subcategoriaId;
			}
			set
			{
				this._subcategoriaId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private Categoria _categoria;
		public virtual Categoria Categoria
		{
			get
			{
				return this._categoria;
			}
			set
			{
				this._categoria = value;
			}
		}
		
		private IList<Documento> _documentos = new List<Documento>();
		public virtual IList<Documento> Documentos
		{
			get
			{
				return this._documentos;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Documento
	{
		private int _documentoId;
		public virtual int DocumentoId
		{
			get
			{
				return this._documentoId;
			}
			set
			{
				this._documentoId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private DateTime _fecha;
		public virtual DateTime Fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				this._fecha = value;
			}
		}
		
		private string _comentarios;
		public virtual string Comentarios
		{
			get
			{
				return this._comentarios;
			}
			set
			{
				this._comentarios = value;
			}
		}
		
		private string _extension;
		public virtual string Extension
		{
			get
			{
				return this._extension;
			}
			set
			{
				this._extension = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
		private Categoria _categoria;
		public virtual Categoria Categoria
		{
			get
			{
				return this._categoria;
			}
			set
			{
				this._categoria = value;
			}
		}
		
		private Subcategoria _subcategoria;
		public virtual Subcategoria Subcategoria
		{
			get
			{
				return this._subcategoria;
			}
			set
			{
				this._subcategoria = value;
			}
		}
		
		private TipoDispositivo _tipoDispositivo;
		public virtual TipoDispositivo TipoDispositivo
		{
			get
			{
				return this._tipoDispositivo;
			}
			set
			{
				this._tipoDispositivo = value;
			}
		}
		
		private IList<InformeProgramado> _informeProgramados = new List<InformeProgramado>();
		public virtual IList<InformeProgramado> InformeProgramados
		{
			get
			{
				return this._informeProgramados;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class GrupoMensajes
	{
		private int _grupoMensajesId;
		public virtual int GrupoMensajesId
		{
			get
			{
				return this._grupoMensajesId;
			}
			set
			{
				this._grupoMensajesId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private IList<Mensaje> _mensajes = new List<Mensaje>();
		public virtual IList<Mensaje> Mensajes
		{
			get
			{
				return this._mensajes;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Mensaje
	{
		private int _mensajeId;
		public virtual int MensajeId
		{
			get
			{
				return this._mensajeId;
			}
			set
			{
				this._mensajeId = value;
			}
		}
		
		private DateTime _fechaInicio;
		public virtual DateTime FechaInicio
		{
			get
			{
				return this._fechaInicio;
			}
			set
			{
				this._fechaInicio = value;
			}
		}
		
		private DateTime _fechaFinal;
		public virtual DateTime FechaFinal
		{
			get
			{
				return this._fechaFinal;
			}
			set
			{
				this._fechaFinal = value;
			}
		}
		
		private string _titulo;
		public virtual string Titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				this._titulo = value;
			}
		}
		
		private string _cuerpo;
		public virtual string Cuerpo
		{
			get
			{
				return this._cuerpo;
			}
			set
			{
				this._cuerpo = value;
			}
		}
		
		private bool _urgente;
		public virtual bool Urgente
		{
			get
			{
				return this._urgente;
			}
			set
			{
				this._urgente = value;
			}
		}
		
		private GrupoMensajes _grupoMensajes;
		public virtual GrupoMensajes GrupoMensajes
		{
			get
			{
				return this._grupoMensajes;
			}
			set
			{
				this._grupoMensajes = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class TipoAnomalia
	{
		private int _tipoAnomaliaId;
		public virtual int TipoAnomaliaId
		{
			get
			{
				return this._tipoAnomaliaId;
			}
			set
			{
				this._tipoAnomaliaId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private IList<Revision> _revisions = new List<Revision>();
		public virtual IList<Revision> Revisions
		{
			get
			{
				return this._revisions;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class ProgramacionInforme
	{
		private int _programacionInformeId;
		public virtual int ProgramacionInformeId
		{
			get
			{
				return this._programacionInformeId;
			}
			set
			{
				this._programacionInformeId = value;
			}
		}
		
		private string _informe;
		public virtual string Informe
		{
			get
			{
				return this._informe;
			}
			set
			{
				this._informe = value;
			}
		}
		
		private string _periodicidad;
		public virtual string Periodicidad
		{
			get
			{
				return this._periodicidad;
			}
			set
			{
				this._periodicidad = value;
			}
		}
		
		private DateTime _fechaInicial;
		public virtual DateTime FechaInicial
		{
			get
			{
				return this._fechaInicial;
			}
			set
			{
				this._fechaInicial = value;
			}
		}
		
		private IList<InformeProgramado> _informeProgramados = new List<InformeProgramado>();
		public virtual IList<InformeProgramado> InformeProgramados
		{
			get
			{
				return this._informeProgramados;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class InformeProgramado
	{
		private int _informeProgramadoId;
		public virtual int InformeProgramadoId
		{
			get
			{
				return this._informeProgramadoId;
			}
			set
			{
				this._informeProgramadoId = value;
			}
		}
		
		private DateTime _fechaInicial;
		public virtual DateTime FechaInicial
		{
			get
			{
				return this._fechaInicial;
			}
			set
			{
				this._fechaInicial = value;
			}
		}
		
		private DateTime _fechaFinal;
		public virtual DateTime FechaFinal
		{
			get
			{
				return this._fechaFinal;
			}
			set
			{
				this._fechaFinal = value;
			}
		}
		
		private ProgramacionInforme _programacionInforme;
		public virtual ProgramacionInforme ProgramacionInforme
		{
			get
			{
				return this._programacionInforme;
			}
			set
			{
				this._programacionInforme = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private Documento _documento;
		public virtual Documento Documento
		{
			get
			{
				return this._documento;
			}
			set
			{
				this._documento = value;
			}
		}
		
		private Instalacion _instalacion;
		public virtual Instalacion Instalacion
		{
			get
			{
				return this._instalacion;
			}
			set
			{
				this._instalacion = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Plantilla
	{
		private int _plantillaId;
		public virtual int PlantillaId
		{
			get
			{
				return this._plantillaId;
			}
			set
			{
				this._plantillaId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _contenido;
		public virtual string Contenido
		{
			get
			{
				return this._contenido;
			}
			set
			{
				this._contenido = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class CargaTerminales
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _archivo;
		public virtual string Archivo
		{
			get
			{
				return this._archivo;
			}
			set
			{
				this._archivo = value;
			}
		}
		
		private DateTime _fecha;
		public virtual DateTime Fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				this._fecha = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class GrupoTrabajo
	{
		private int _grupoTrabajoId;
		public virtual int GrupoTrabajoId
		{
			get
			{
				return this._grupoTrabajoId;
			}
			set
			{
				this._grupoTrabajoId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private IList<Usuario> _usuarios = new List<Usuario>();
		public virtual IList<Usuario> Usuarios
		{
			get
			{
				return this._usuarios;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Incidencia
	{
		private int _incidenciaId;
		public virtual int IncidenciaId
		{
			get
			{
				return this._incidenciaId;
			}
			set
			{
				this._incidenciaId = value;
			}
		}
		
		private DateTime _fechaApertura;
		public virtual DateTime FechaApertura
		{
			get
			{
				return this._fechaApertura;
			}
			set
			{
				this._fechaApertura = value;
			}
		}
		
		private string _comentarios;
		public virtual string Comentarios
		{
			get
			{
				return this._comentarios;
			}
			set
			{
				this._comentarios = value;
			}
		}
		
		private bool _operativo;
		public virtual bool Operativo
		{
			get
			{
				return this._operativo;
			}
			set
			{
				this._operativo = value;
			}
		}
		
		private DateTime? _fechaCierre;
		public virtual DateTime? FechaCierre
		{
			get
			{
				return this._fechaCierre;
			}
			set
			{
				this._fechaCierre = value;
			}
		}
		
		private DateTime? _fechaPrevista;
		public virtual DateTime? FechaPrevista
		{
			get
			{
				return this._fechaPrevista;
			}
			set
			{
				this._fechaPrevista = value;
			}
		}
		
		private bool _siguePlan;
		public virtual bool SiguePlan
		{
			get
			{
				return this._siguePlan;
			}
			set
			{
				this._siguePlan = value;
			}
		}
		
		private Usuario _usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				this._usuario = value;
			}
		}
		
		private Dispositivo _dispositivo;
		public virtual Dispositivo Dispositivo
		{
			get
			{
				return this._dispositivo;
			}
			set
			{
				this._dispositivo = value;
			}
		}
		
		private Estado _estado;
		public virtual Estado Estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				this._estado = value;
			}
		}
		
		private Prioridad _prioridad;
		public virtual Prioridad Prioridad
		{
			get
			{
				return this._prioridad;
			}
			set
			{
				this._prioridad = value;
			}
		}
		
		private Responsable _responsable;
		public virtual Responsable Responsable
		{
			get
			{
				return this._responsable;
			}
			set
			{
				this._responsable = value;
			}
		}
		
		private IList<IncidenciaEvolucion> _incidenciaEvolucions = new List<IncidenciaEvolucion>();
		public virtual IList<IncidenciaEvolucion> IncidenciaEvolucions
		{
			get
			{
				return this._incidenciaEvolucions;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class IncidenciaEvolucion
	{
		private int _incidenciaEvolucionId;
		public virtual int IncidenciaEvolucionId
		{
			get
			{
				return this._incidenciaEvolucionId;
			}
			set
			{
				this._incidenciaEvolucionId = value;
			}
		}
		
		private DateTime _fechaEvolucion;
		public virtual DateTime FechaEvolucion
		{
			get
			{
				return this._fechaEvolucion;
			}
			set
			{
				this._fechaEvolucion = value;
			}
		}
		
		private string _comentarios;
		public virtual string Comentarios
		{
			get
			{
				return this._comentarios;
			}
			set
			{
				this._comentarios = value;
			}
		}
		
		private bool _operativo;
		public virtual bool Operativo
		{
			get
			{
				return this._operativo;
			}
			set
			{
				this._operativo = value;
			}
		}
		
		private Incidencia _incidencia;
		public virtual Incidencia Incidencia
		{
			get
			{
				return this._incidencia;
			}
			set
			{
				this._incidencia = value;
			}
		}
		
		private Usuario _usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				this._usuario = value;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Estado
	{
		private int _estadoId;
		public virtual int EstadoId
		{
			get
			{
				return this._estadoId;
			}
			set
			{
				this._estadoId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private bool _enApertura;
		public virtual bool EnApertura
		{
			get
			{
				return this._enApertura;
			}
			set
			{
				this._enApertura = value;
			}
		}
		
		private bool _enCierre;
		public virtual bool EnCierre
		{
			get
			{
				return this._enCierre;
			}
			set
			{
				this._enCierre = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private IList<Incidencia> _incidencias = new List<Incidencia>();
		public virtual IList<Incidencia> Incidencias
		{
			get
			{
				return this._incidencias;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Prioridad
	{
		private int _prioridadId;
		public virtual int PrioridadId
		{
			get
			{
				return this._prioridadId;
			}
			set
			{
				this._prioridadId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private IList<Incidencia> _incidencias = new List<Incidencia>();
		public virtual IList<Incidencia> Incidencias
		{
			get
			{
				return this._incidencias;
			}
		}
		
	}
}
namespace LainsaSciModelo	
{
	public partial class Responsable
	{
		private int _responsableId;
		public virtual int ResponsableId
		{
			get
			{
				return this._responsableId;
			}
			set
			{
				this._responsableId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private Empresa _empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private IList<Incidencia> _incidencias = new List<Incidencia>();
		public virtual IList<Incidencia> Incidencias
		{
			get
			{
				return this._incidencias;
			}
		}
		
	}
}
#pragma warning restore 1591
