//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadFilter {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadFilter.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir expresión.
        /// </summary>
        internal static string AddExpressionToolTip {
            get {
                return ResourceManager.GetString("AddExpressionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir grupo.
        /// </summary>
        internal static string AddGroupToolTip {
            get {
                return ResourceManager.GetString("AddGroupToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar.
        /// </summary>
        internal static string ApplyButtonText {
            get {
                return ResourceManager.GetString("ApplyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Y.
        /// </summary>
        internal static string BetweenDelimeterText {
            get {
                return ResourceManager.GetString("BetweenDelimeterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entre.
        /// </summary>
        internal static string FilterFunctionBetween {
            get {
                return ResourceManager.GetString("FilterFunctionBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contiene.
        /// </summary>
        internal static string FilterFunctionContains {
            get {
                return ResourceManager.GetString("FilterFunctionContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No contiene.
        /// </summary>
        internal static string FilterFunctionDoesNotContain {
            get {
                return ResourceManager.GetString("FilterFunctionDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acaba con.
        /// </summary>
        internal static string FilterFunctionEndsWith {
            get {
                return ResourceManager.GetString("FilterFunctionEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Igual a.
        /// </summary>
        internal static string FilterFunctionEqualTo {
            get {
                return ResourceManager.GetString("FilterFunctionEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor que.
        /// </summary>
        internal static string FilterFunctionGreaterThan {
            get {
                return ResourceManager.GetString("FilterFunctionGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor o igual que.
        /// </summary>
        internal static string FilterFunctionGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterFunctionGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Está vacío.
        /// </summary>
        internal static string FilterFunctionIsEmpty {
            get {
                return ResourceManager.GetString("FilterFunctionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es nulo.
        /// </summary>
        internal static string FilterFunctionIsNull {
            get {
                return ResourceManager.GetString("FilterFunctionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menor que.
        /// </summary>
        internal static string FilterFunctionLessThan {
            get {
                return ResourceManager.GetString("FilterFunctionLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menor o igual que.
        /// </summary>
        internal static string FilterFunctionLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterFunctionLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No entre.
        /// </summary>
        internal static string FilterFunctionNotBetween {
            get {
                return ResourceManager.GetString("FilterFunctionNotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No igual a .
        /// </summary>
        internal static string FilterFunctionNotEqualTo {
            get {
                return ResourceManager.GetString("FilterFunctionNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No está vacío.
        /// </summary>
        internal static string FilterFunctionNotIsEmpty {
            get {
                return ResourceManager.GetString("FilterFunctionNotIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es nulo.
        /// </summary>
        internal static string FilterFunctionNotIsNull {
            get {
                return ResourceManager.GetString("FilterFunctionNotIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comienza con.
        /// </summary>
        internal static string FilterFunctionStartsWith {
            get {
                return ResourceManager.GetString("FilterFunctionStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a And.
        /// </summary>
        internal static string GroupOperationAnd {
            get {
                return ResourceManager.GetString("GroupOperationAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not And.
        /// </summary>
        internal static string GroupOperationNotAnd {
            get {
                return ResourceManager.GetString("GroupOperationNotAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not Or.
        /// </summary>
        internal static string GroupOperationNotOr {
            get {
                return ResourceManager.GetString("GroupOperationNotOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Or.
        /// </summary>
        internal static string GroupOperationOr {
            get {
                return ResourceManager.GetString("GroupOperationOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar item.
        /// </summary>
        internal static string RemoveToolTip {
            get {
                return ResourceManager.GetString("RemoveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor no elimine esta clave.
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
    }
}
